# sls cloud organizstion target
org: hei
# sls cloud app name
app: real-time-chat-saas-app
# sls cloud service prefix name
service: real-time-chat-be
# default deployment to singapore
region: ap-southeast-1
# default deployment aws profile set to
profile: hei