# sls cloud organizstion target
org: hei
# sls cloud app name
app: chat-room-saas-app
# sls cloud service prefix name
service: chat-room-be
# default deployment to singapore
region: ap-southeast-1
# default deployment aws profile set to
profile: hei