service: ${file(../../service.yml):service}-user

# Framework version constraint (semver constraint): '3', '^2.33'
frameworkVersion: '3'

params: ${file(../../params.yml)}

provider: 
  name: aws
  deploymentMethod: direct
  region: ap-southeast-1
  profile: ${file(../../service.yml):profile}
  runtime: nodejs18.x
  # stackName: ${self:service}-stack-${opt:stage, self:provider.stage}
  stage: ${opt:stage, self:provider.stage}
  memorySize: 256
  timeout: 30
  architecture: arm64
  environment:
    POST_WSCAT: ${param:post-wscat}
    STAGE: ${opt:stage, self:provider.stage}
    DB_USER: ${param:db-username}
    DB_NAME: ${param:db-name}
    DATABASE_URL: 
      Fn::Join: 
        - ''
        - - "postgresql://"
          - ${param:db-username}
          - ":"
          - ${param:db-password}
          - ${param:db-host}
          - ${param:db-name}
          - "?sslmode=verify-full"

  # httpApi:
  #   cors: true
  #   authorizers:
  #     someJwtAuthorizer:
  #       type: jwt
  #       identitySource: $request.header.Authorization
  #       issuerUrl: https://cognito-idp.${opt:region, self:provider.region}.amazonaws.com/${param:UserPoolId}
  #       audience: 
  #         - '${param:UserPoolClient}'

package:
  patterns:
    - "!layerSourceTarball.tar.gz"

layers:
  RealTimeChatCommonLibrary:
    path: ../../common-library
  RealTimeChatNpmLibrary:
    path: ../../npm-library

functions:
  get-user:
    handler: src/user.get
    layers:
      - !Ref RealTimeChatCommonLibraryLambdaLayer
      - !Ref RealTimeChatNpmLibraryLambdaLayer
    events:
      - httpApi:
            method: GET
            path: /user
            cors: true
            # authorizer:
            #   name: someJwtAuthorizer
  count-user:
    handler: src/user.count
    layers:
      - !Ref RealTimeChatCommonLibraryLambdaLayer
      - !Ref RealTimeChatNpmLibraryLambdaLayer
    events:
      - httpApi:
            method: GET
            path: /user/count
            cors: true
            # authorizer:
            #   name: someJwtAuthorizer
  create-user:
    handler: src/user.create
    layers:
      - !Ref RealTimeChatCommonLibraryLambdaLayer
      - !Ref RealTimeChatNpmLibraryLambdaLayer
    events:
      - httpApi:
            method: POST
            path: /user
            cors: true
            # authorizer:
            #   name: someJwtAuthorizer
  update-user:
    handler: src/user.update
    layers:
      - !Ref RealTimeChatCommonLibraryLambdaLayer
      - !Ref RealTimeChatNpmLibraryLambdaLayer
    events:
      - httpApi:
            method: PUT
            path: /user/{id}
            cors: true
            # authorizer:
            #   name: someJwtAuthorizer
  delete-user:
    handler: src/user.delete
    layers:
      - !Ref RealTimeChatCommonLibraryLambdaLayer
      - !Ref RealTimeChatNpmLibraryLambdaLayer
    events:
      - httpApi:
            method: DELETE
            path: /user/{id}
            cors: true
            # authorizer:
            #   name: someJwtAuthorizer


plugins:
  - serverless-offline
